apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "trade-bench.fullname" . }}-orchestrator
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: orchestrator
  template:
    metadata:
      labels:
        app: orchestrator
    spec:
      serviceAccountName: orchestrator-sa
      containers:
        - name: orchestrator
          image: {{ .Values.orchestrator.image }}
          ports:
            - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "trade-bench.fullname" . }}-orchestrator
spec:
  type: {{ .Values.orchestrator.service.type }}
  ports:
    - port: {{ .Values.orchestrator.service.port }}
      targetPort: 8080
  selector:
    app: orchestrator
